package com.kotsin.consumer.enrichment.signal;

import com.kotsin.consumer.enrichment.signal.model.TradingSignal;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.Collections;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

/**
 * SignalGenerator - Legacy signal generation service
 *
 * NOTE: Signal generation has been moved to InstrumentStateManager (state machine).
 * This class is kept for backward compatibility with stats and caching.
 *
 * The InstrumentStateManager implements the new state machine architecture:
 * IDLE → WATCHING → READY → POSITIONED → COOLDOWN
 *
 * See: com.kotsin.consumer.trading.state.InstrumentStateManager
 */
@Slf4j
@Service
public class SignalGenerator {

    /**
     * Signal cache - kept for backward compatibility
     */
    private final ConcurrentHashMap<String, List<TradingSignal>> signalCache = new ConcurrentHashMap<>();

    /**
     * Statistics tracking
     */
    private final GeneratorStats stats = new GeneratorStats();

    /**
     * Get cached signals for a family
     * Note: Signals are now generated by InstrumentStateManager
     */
    public List<TradingSignal> getCachedSignals(String familyId) {
        return signalCache.getOrDefault(familyId, Collections.emptyList());
    }

    /**
     * Clear cached signals for a family
     */
    public void clearCache(String familyId) {
        signalCache.remove(familyId);
    }

    /**
     * Get generator statistics
     */
    public GeneratorStats getStats() {
        return stats;
    }

    /**
     * Statistics class for backward compatibility
     */
    @Data
    public static class GeneratorStats {
        private long totalSignalsGenerated = 0;
        private long totalPatternSignals = 0;
        private long totalSetupSignals = 0;
        private long totalForecastSignals = 0;
        private long totalFilteredOut = 0;
        private long avgProcessingTimeMs = 0;

        @Override
        public String toString() {
            return String.format("SignalGenerator: %d signals (pattern=%d, setup=%d, forecast=%d), %d filtered",
                    totalSignalsGenerated, totalPatternSignals, totalSetupSignals, totalForecastSignals, totalFilteredOut);
        }
    }
}
